version: '3.1'
services:
  app:
    restart: always
    image: kharkiv_bot:v1
    container_name: kharkiv_app
    volumes:
      - ./volumes/files:/workdir/files:z
    depends_on:
      - kharkiv_postgresql
    environment:
      - SERVER_PORT=80
      - BOT1_NAME=Kharkiv flat rental
      - BOT1_TOKEN=1635315389:AAHRRMb2AetKfE0ufEeLDkRvmzrQLzGYU3P
      - BOT2_NAME=test bot 2
      - BOT2_TOKEN=163641874:ABGp-scGObaswHgOm8HkB7e8-mVXoORd3ac
      - SPRING_DATASOURCE_URL=jdbc:postgresql://kharkiv_postgresql:5432/kharkiv
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - DDL_AUTO=none
      - JPA_SHOW_SQL=false
      - ADMIN_PASSWORD=1234
      - TELEGRAM_CHANNEL=@kvartiry_kharkov
      - THREADS_CORE_POOL_SIZE=40
      - THREADS_MAX_POOL_SIZE=60
      - THREADS_QUEUE_CAPACITY=10
      - DELAY_DATABASE_SAVE_CACHE=1000
      - DELAY_USER_SPAM=600
      - USER_FLATS_NUMBER=2
      - MAX_MSG_PER_SECOND=30
      - MAX_API_PER_SECOND=30
      - TIME_IN_CACHE=5
  kharkiv_postgresql:
    restart: always
    image: postgres:12
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kharkiv
      - PGDATA=/var/lib/postgresql/data
